name: Feature Request
description: Suggest a new feature or enhancement for the OpenTelemetry Proto definitions
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! 🚀
        
        Before submitting, please search existing issues to avoid duplicates.
        
  - type: textarea
    id: problem
    attributes:
      label: Is your feature request related to a problem?
      description: A clear and concise description of what the problem is.
      placeholder: I'm always frustrated when... / It's difficult to... / There's no way to...
    validations:
      required: true
      
  - type: textarea
    id: solution
    attributes:
      label: Describe the solution you'd like
      description: A clear and concise description of what you want to happen.
      placeholder: I would like the proto definitions to include...
    validations:
      required: true
      
  - type: textarea
    id: alternatives
    attributes:
      label: Describe alternatives you've considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: I've considered... / Another approach could be...
      
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: |
        Please describe your use case and how this feature would benefit you and others.
        Include examples of how you would use this feature.
      placeholder: |
        This feature would help with...
        For example, I would use it to...
    validations:
      required: true
      
  - type: textarea
    id: proto-changes
    attributes:
      label: Proposed Proto Changes
      description: |
        If you have specific ideas about how the proto definitions should change, please describe them here.
        Include any proposed message structures, field names, or other details.
      placeholder: |
        I propose adding a new message/field:
        ```protobuf
        // Example proto definition
        ```
        
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context about the feature request here, such as:
        - Related specifications or standards
        - Links to discussions or documentation
        - Impact on existing implementations
      placeholder: Any additional information that might be relevant...
      
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0