name: Other
description: For questions, discussions, or other issues that don't fit the above categories
labels: ["question"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for your submission! 💬
        
        Before submitting, please search existing issues to avoid duplicates.
        
  - type: dropdown
    id: issue-type
    attributes:
      label: Issue Type
      description: What type of issue is this?
      options:
        - Question about proto definitions
        - Discussion about proto design
        - Documentation issue
        - Build/tooling issue
        - Other
    validations:
      required: true
      
  - type: textarea
    id: description
    attributes:
      label: Description
      description: A clear and concise description of your question, discussion topic, or issue.
      placeholder: Please describe your question or issue in detail...
    validations:
      required: true
      
  - type: textarea
    id: proto-files
    attributes:
      label: Related Proto Files
      description: |
        Which proto files or definitions are related to your question/issue?
        List the specific files or message types if applicable.
      placeholder: |
        e.g. opentelemetry/proto/trace/v1/trace.proto
        e.g. Span message definition
        
  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: |
        Add any other context that might be helpful, such as:
        - Your use case or scenario
        - Language/framework you're using
        - Links to relevant documentation
        - Code examples
      placeholder: Any additional information that might be relevant...
      
  - type: dropdown
    attributes:
      label: Tip
      description: This element is static, used to render a helpful sub-heading for end-users and community members to help prioritize issues. Please leave as is.
      options:
        - <sub>[React](https://github.blog/news-insights/product-news/add-reactions-to-pull-requests-issues-and-comments/) with 👍 to help prioritize this issue. Please use comments to provide useful context, avoiding `+1` or `me too`, to help us triage it. Learn more [here](https://opentelemetry.io/community/end-user/issue-participation/).</sub>
      default: 0